# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91601f02a30bc98c8dbb37cba8d31bece95f03f909af2dbc8cbf476ca1d8c59e3539ae381991c38798fd7d6b1911e201fab0d4114a13fa8cf79c666978acd991

test:
  secret_key_base: 1748d99afb912832ce7075dc0a3e2fe50f620deeaaac61416c4c247fdb74c9bd95df4ba62173098d67d9318f6b731c0be633e4a12f40dec4b39ef5f64c5a4c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
